# -*- coding: utf-8 -*-
"""sample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJUbtIev_r3ikPin_F7yNXFZZ9XPYvDR
"""

print('Helo Srikanth')